name: Publish code coverage
on:
  push:
    branches: ["Presentation"]
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Log recent commit
        run: git log -1

      - name: Files in the project
        run: ls -R

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clean with Maven
        run: mvn clean verify

      - name: Zip code coverage report directory
        run: zip -r coverage-report.zip target/site

      - name: Upload code coverage report to google drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "coverage-report.zip"
          folderId: ${{ secrets.folderId }}
          name: "coverage-report.zip" # optional string
          overwrite: "true" # optional boolean