# .github/workflows/main.yml
name: Publish JAR file
on:
  workflow_dispatch:
    branches:
      - Development
      - Presentation
      - Controlller
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clean with Maven
        run: mvn clean --file pom.xml

      - name: Package the maven project
        run: mvn -B package --file pom.xml

      - name: Create executable Jar File
        run: mvn clean compile assembly:single

      - name: Upload java executable to google drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "target/JabberPoint-1.0-SNAPSHOT-jar-with-dependencies.jar"
          folderId: ${{ secrets.folderId }}
          name: "Java.jar" # optional string
          overwrite: "true" # optional boolean

